### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by cyk2018** [jeremyxu2010/toy-compiler#1]
非常感谢您！

我是电子科技大学一名本科生，最近在学习编译原理的课程，参考了《LLVM Cookbook》一书，书中通过C++自定义了词法分析器和语法分析器，我下载了随书附赠的源码，但并不能运行，因此我想尝试通过flex和bison生成词法分析器和语法分析器，结合LLVM 提供的 API 生成对应的 LLVM IR，然后利用LLVM生成代码。

在网络上，我看到了[自制toy-compiler](https://gnuu.org/2009/09/18/writing-your-own-toy-compiler/)这篇文章，但是其成文的时间较早，很多头文件在较新的版本中已经有所不同，我在作者的github代码库中获得了最新的代码，仍然不能运行。

当我处于放弃的边缘时，我看到了您写的文章，找到了这份代码库，您对代码进行了很好的修改，除了一点小小的问题，修改了之后可以顺利的通过，并运行，非常感谢！

这个问题，是在编译时添加了-lz参数，我不知道为什么？可能是因为我未安装某些软件？期待您的回答。

**Comment by jeremyxu2010** [comment]
你本机少装了libz库。 参考命令：brew install zlib

cyk2018 ***@***.***>于2021年5月3日 周一下午6:05写道：

**Comment by cyk2018** [comment]
好的，我明白了，谢谢了
